import { createServer } from "node:http";
import { appendFile, mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { basename, extname, join, normalize } from "node:path";
import { fileURLToPath } from "node:url";
import { getGreekOccurrencesByStrongs } from "./src/data/cgvData.js";

const rootDir = fileURLToPath(new URL(".", import.meta.url));
const publicDir = join(rootDir, "public");
const investigationsDir = join(rootDir, "investigations");
const port = Number(process.env.PORT || 1424);

const tabs = [
  { id: "README", file: "README.md" },
  { id: "Observations", file: "observations.md" },
  { id: "Questions", file: "questions.md" },
  { id: "Evidence", file: "evidence.md" },
  { id: "Research", file: "research.md" },
  { id: "Policy", file: "policy.md" },
  { id: "History", file: "history.md" }
];

const contentTypes = {
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml"
};

function send(response, status, body, contentType = "text/plain; charset=utf-8") {
  response.writeHead(status, {
    "Content-Type": contentType,
    "Cache-Control": "no-store"
  });
  response.end(body);
}

function sendJson(response, status, body) {
  send(response, status, JSON.stringify(body), "application/json; charset=utf-8");
}

function safeInvestigationPath(id) {
  if (!/^INV-\d{4}$/.test(id)) {
    throw new Error("Invalid investigation ID");
  }
  return join(investigationsDir, id);
}

function safeTabFile(file) {
  const tab = tabs.find(item => item.file === file);
  if (!tab) {
    throw new Error("Invalid investigation file");
  }
  return tab;
}

function safeEvidenceFile(file) {
  if (!/^[a-z0-9-]+\.md$/.test(file)) {
    throw new Error("Invalid evidence file");
  }
  return file;
}

function todayIsoDate() {
  return new Date().toLocaleDateString("en-CA", { timeZone: "America/La_Paz" });
}

function formatOccurrenceEvidence(report, generatedAt) {
  const evidenceFields = [
    ["Greek context", occurrence => occurrence.greekText],
    ["Surface form", occurrence => occurrence.surfaceForm],
    ["Lemma", occurrence => occurrence.lemma],
    ["Strong's", occurrence => occurrence.strongs],
    ["RMAC", occurrence => occurrence.morphology],
    ["Project Literal", occurrence => occurrence.translations?.projectLiteral],
    ["BLE", occurrence => occurrence.translations?.ble],
    ["RV1862", occurrence => occurrence.translations?.rv1862],
    ["RV1909", occurrence => occurrence.translations?.rv1909],
    ["SPNBES", occurrence => occurrence.translations?.spnbes],
    ["SPNVBL", occurrence => occurrence.translations?.spnvbl]
  ];

  const occurrenceSections = report.occurrences.map(occurrence => {
    const fields = evidenceFields.map(([label, readValue]) => {
      const value = readValue(occurrence);
      return `**${label}**\n\n${value || "—"}`;
    }).join("\n\n");

    return `### ${occurrence.reference}\n\n${fields}\n\n---`;
  }).join("\n\n");

  return `# Evidence Matrix — ${report.subject}

## Metadata

Investigation: INV-0001  
Subject: ${report.subject}  
Source: cgv-data  
Source NT: SBLGNT via MorphGNT  
Generated by: cgv-translator prototype  
Generated at: ${generatedAt}  

## Summary

Total occurrences: ${report.occurrences.length}

## Evidence Blocks

${occurrenceSections}
`;
}

function readMarkdownValue(markdown, heading) {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const headingIndex = lines.findIndex(line => line.trim() === `## ${heading}`);
  if (headingIndex === -1) return "";

  for (let index = headingIndex + 1; index < lines.length; index += 1) {
    const line = lines[index].trim();
    if (!line || line === "---") continue;
    if (line.startsWith("#")) return "";
    return line;
  }

  return "";
}

function readOriginValue(markdown, label) {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n").map(line => line.trim());
  const originIndex = lines.findIndex(line => line === "## Origin");
  if (originIndex === -1) return "";

  const nextSection = lines.findIndex((line, index) => index > originIndex && line.startsWith("## "));
  const end = nextSection === -1 ? lines.length : nextSection;

  for (let index = originIndex + 1; index < end; index += 1) {
    if (lines[index] !== label) continue;
    for (let valueIndex = index + 1; valueIndex < end; valueIndex += 1) {
      const value = lines[valueIndex];
      if (!value || value === "---") continue;
      return value.startsWith("#") ? "" : value;
    }
  }

  return "";
}

async function readInvestigationMeta(id, investigationDir) {
  const readme = await readFile(join(investigationDir, "README.md"), "utf8").catch(() => "");
  return {
    id,
    primarySubject: readMarkdownValue(readme, "Primary Subject"),
    originReference: readOriginValue(readme, "Reference"),
    currentStatus: readMarkdownValue(readme, "Current Status")
  };
}

async function readJsonBody(request) {
  const chunks = [];
  for await (const chunk of request) {
    chunks.push(chunk);
  }
  const raw = Buffer.concat(chunks).toString("utf8");
  return raw ? JSON.parse(raw) : {};
}

async function sendEvidenceMarkdown(response, id, fileName) {
  const investigationDir = safeInvestigationPath(id);
  const evidenceDir = join(investigationDir, "evidence");
  const safeFileName = safeEvidenceFile(decodeURIComponent(fileName));
  const content = await readFile(join(evidenceDir, safeFileName), "utf8").catch(() => "");
  if (!content) {
    send(response, 404, "Not found");
    return;
  }
  send(response, 200, content, "text/markdown; charset=utf-8");
}

async function handleApi(request, response, url) {
  if (request.method === "GET" && url.pathname === "/api/investigations") {
    const entries = await readdir(investigationsDir, { withFileTypes: true }).catch(() => []);
    const investigations = entries
      .filter(entry => entry.isDirectory() && /^INV-\d{4}$/.test(entry.name))
      .map(entry => entry.name)
      .sort();
    sendJson(response, 200, { investigations });
    return;
  }

  const evidenceMatch = url.pathname.match(/^\/api\/investigations\/(INV-\d{4})\/evidence(?:\/([^/]+))?$/);
  if (evidenceMatch) {
    const [, id, fileName] = evidenceMatch;
    const investigationDir = safeInvestigationPath(id);
    const evidenceDir = join(investigationDir, "evidence");

    if (request.method === "GET" && !fileName) {
      const entries = await readdir(evidenceDir, { withFileTypes: true }).catch(() => []);
      const files = entries
        .filter(entry => entry.isFile() && entry.name.endsWith(".md") && entry.name !== "README.md")
        .map(entry => ({ name: entry.name, path: `evidence/${entry.name}` }))
        .sort((left, right) => left.name.localeCompare(right.name));
      sendJson(response, 200, { id, files });
      return;
    }

    if (request.method === "GET" && fileName) {
      await sendEvidenceMarkdown(response, id, fileName);
      return;
    }

    sendJson(response, 405, { error: "Method not allowed" });
    return;
  }

  const gatherMatch = url.pathname.match(/^\/api\/investigations\/(INV-\d{4})\/gather$/);
  if (gatherMatch) {
    const [, id] = gatherMatch;
    const investigationDir = safeInvestigationPath(id);

    if (request.method !== "POST") {
      sendJson(response, 405, { error: "Method not allowed" });
      return;
    }

    const body = await readJsonBody(request);
    if (body.type !== "occurrences") {
      sendJson(response, 400, { error: "Only occurrence gathering is implemented" });
      return;
    }

    const evidenceDir = join(investigationDir, "evidence");
    const fileName = "occurrences.md";
    const filePath = join(evidenceDir, fileName);
    const exists = await stat(filePath).then(() => true).catch(() => false);

    if (exists && body.replace !== true) {
      sendJson(response, 409, {
        code: "EVIDENCE_EXISTS",
        error: "occurrences.md already exists"
      });
      return;
    }

    const report = await getGreekOccurrencesByStrongs("G1401");
    const generatedAt = new Date().toISOString();
    const occurrenceEvidence = formatOccurrenceEvidence(report, generatedAt);

    await mkdir(evidenceDir, { recursive: true });
    await writeFile(filePath, occurrenceEvidence.endsWith("\n") ? occurrenceEvidence : `${occurrenceEvidence}\n`, "utf8");
    await appendFile(
      join(investigationDir, "history.md"),
      `\n## ${todayIsoDate()}\n\nGenerated occurrence evidence from cgv-data for G1401 δοῦλος.\n`,
      "utf8"
    );

    sendJson(response, 200, {
      generated: true,
      replaced: exists,
      file: { name: basename(filePath), path: `evidence/${fileName}` }
    });
    return;
  }

  const match = url.pathname.match(/^\/api\/investigations\/(INV-\d{4})(?:\/files\/([^/]+))?$/);
  if (!match) {
    sendJson(response, 404, { error: "Not found" });
    return;
  }

  const [, id, fileName] = match;
  const investigationDir = safeInvestigationPath(id);

  if (request.method === "GET" && !fileName) {
    const files = await Promise.all(
      tabs.map(async tab => {
        const path = join(investigationDir, tab.file);
        const exists = await stat(path).then(() => true).catch(() => false);
        return { ...tab, exists };
      })
    );
    const meta = await readInvestigationMeta(id, investigationDir);
    sendJson(response, 200, { id, meta, files });
    return;
  }

  if (!fileName) {
    sendJson(response, 405, { error: "Method not allowed" });
    return;
  }

  const tab = safeTabFile(decodeURIComponent(fileName));
  const filePath = join(investigationDir, tab.file);

  if (request.method === "GET") {
    const content = await readFile(filePath, "utf8").catch(() => "");
    sendJson(response, 200, { id, tab: tab.id, file: tab.file, content });
    return;
  }

  if (request.method === "PUT") {
    const body = await readJsonBody(request);
    const content = typeof body.content === "string" ? body.content : "";
    await writeFile(filePath, content.endsWith("\n") ? content : `${content}\n`, "utf8");
    sendJson(response, 200, { saved: true, id, tab: tab.id, file: tab.file });
    return;
  }

  sendJson(response, 405, { error: "Method not allowed" });
}

async function handleStatic(response, url) {
  const requested = url.pathname === "/" ? "/index.html" : url.pathname;
  const path = normalize(join(publicDir, requested));
  if (!path.startsWith(publicDir)) {
    send(response, 403, "Forbidden");
    return;
  }

  try {
    const content = await readFile(path);
    send(response, 200, content, contentTypes[extname(path)] || "application/octet-stream");
  } catch {
    send(response, 404, "Not found");
  }
}

createServer(async (request, response) => {
  try {
    const url = new URL(request.url || "/", `http://${request.headers.host}`);
    if (url.pathname.startsWith("/api/")) {
      await handleApi(request, response, url);
      return;
    }

    const evidenceAliasMatch = url.pathname.match(/^\/(?:investigations\/(INV-\d{4})\/)?evidence\/([^/]+)$/);
    if (request.method === "GET" && evidenceAliasMatch) {
      const [, id = "INV-0001", fileName] = evidenceAliasMatch;
      await sendEvidenceMarkdown(response, id, fileName);
      return;
    }

    await handleStatic(response, url);
  } catch (error) {
    sendJson(response, 500, { error: error instanceof Error ? error.message : String(error) });
  }
}).listen(port, "127.0.0.1", () => {
  console.log(`CGV Translator prototype: http://127.0.0.1:${port}/`);
});
